export const commentsData = [
  {
    name: "Mohd Moazzam",
    text: "Lorem ipsum dolar sit amet",
    replies: [
      {
        name: "Mohd Moazzam",
        text: "Lorem ipsum dolar sit amet",
        replies: [],
      },
      {
        name: "Mohd Moazzam",
        text: "Lorem ipsum dolar sit amet",
        replies: [
          {
            name: "Mohd Moazzam",
            text: "Lorem ipsum dolar sit amet",
            replies: [
              {
                name: "Mohd Moazzam",
                text: "Lorem ipsum dolar sit amet",
                replies: [
                  {
                    name: "Mohd Moazzam",
                    text: "Lorem ipsum dolar sit amet",
                    replies: [],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Mohd Moazzam",
    text: "Lorem ipsum dolar sit amet",
    replies: [],
  },
  {
    name: "Mohd Moazzam",
    text: "Lorem ipsum dolar sit amet",
    replies: [],
  },
  {
    name: "Mohd Moazzam",
    text: "Lorem ipsum dolar sit amet",
    replies: [],
  },
];

export const firstNames = [
  "John",
  "Jane",
  "Alex",
  "Chris",
  "Pat",
  "Taylor",
  "Jordan",
  "Casey",
  "Morgan",
  "Riley",
  "Sam",
  "Jamie",
  "Avery",
  "Cameron",
  "Parker",
  "Sydney",
  "Dakota",
  "Skyler",
  "Harper",
  "Reese",
  "Quinn",
  "Rowan",
  "Sage",
  "Rory",
  "Blake",
  "Finley",
  "Sawyer",
  "Elliot",
  "Mason",
  "Logan",
  "Hunter",
  "Dylan",
  "Tyler",
  "Reagan",
  "Jordan",
  "Kendall",
  "Payton",
  "Aiden",
  "Hayden",
  "Jaden",
  "Kai",
  "Phoenix",
  "Riley",
  "Shay",
  "River",
  "Zion",
  "Emerson",
  "Aspen",
  "Bailey",
  "Carter",
  "Evelyn",
  "Amelia",
  "Liam",
  "Noah",
  "Olivia",
  "Emma",
  "Sophia",
  "Isabella",
  "Mia",
  "Charlotte",
  "Mila",
  "Benjamin",
  "Elijah",
  "Lucas",
  "Henry",
  "James",
  "Alexander",
  "Sebastian",
  "Jack",
  "Oliver",
  "Aurora",
  "Luna",
  "Aria",
  "Grace",
  "Chloe",
  "Lily",
  "Zoey",
  "Levi",
  "Wyatt",
  "Owen",
  "Eliana",
  "Eva",
  "Camila",
  "Eleanor",
  "Hannah",
  "Ella",
  "Madison",
  "Scarlett",
  "Riley",
  "Sofia",
  "Emily",
  "Layla",
  "Zoe",
  "Lillian",
  "Abigail",
  "Penelope",
  "Lucy",
  "Bella",
  "Nora",
  "Ivy",
];

export const lastNames = [
  "Smith",
  "Johnson",
  "Williams",
  "Brown",
  "Jones",
  "Garcia",
  "Miller",
  "Davis",
  "Martinez",
  "Lopez",
  "Gonzalez",
  "Wilson",
  "Anderson",
  "Thomas",
  "Taylor",
  "Moore",
  "Jackson",
  "Martin",
  "Lee",
  "Perez",
  "Thompson",
  "White",
  "Harris",
  "Sanchez",
  "Clark",
  "Ramirez",
  "Lewis",
  "Robinson",
  "Walker",
  "Young",
  "Allen",
  "King",
  "Wright",
  "Scott",
  "Torres",
  "Nguyen",
  "Hill",
  "Flores",
  "Green",
  "Adams",
  "Baker",
  "Nelson",
  "Hall",
  "Rivera",
  "Campbell",
  "Mitchell",
  "Carter",
  "Roberts",
  "Gomez",
  "Phillips",
  "Turner",
  "Parker",
  "Evans",
  "Edwards",
  "Collins",
  "Stewart",
  "Morris",
  "Ortiz",
  "Reed",
  "Cook",
  "Morgan",
  "Bell",
  "Murphy",
  "Bailey",
  "Rivera",
  "Cooper",
  "Richardson",
  "Cox",
  "Howard",
  "Ward",
  "Peterson",
  "Gray",
  "Ramsey",
  "Sanders",
  "Bryant",
  "Foster",
  "Day",
  "Morales",
  "Reynolds",
  "Powell",
  "Russell",
  "Fisher",
  "Ellis",
  "Gardner",
  "Duncan",
  "Arnold",
  "Hughes",
  "Fox",
  "Kennedy",
  "Hansen",
  "Graham",
  "Simmons",
  "Wallace",
  "Pearson",
  "Boone",
  "Rhodes",
  "Barnes",
  "Mason",
  "Bennett",
  "Knight",
];

export const messages = [
  "Hello, how are you?",
  "What's up?",
  "Good morning!",
  "Have a great day!",
  "See you later!",
  "Thank you!",
  "I'm on my way.",
  "Let's catch up soon!",
  "Can you help me with this?",
  "Nice to meet you!",
  "Happy birthday!",
  "Congratulations!",
  "Good luck!",
  "I miss you.",
  "Call me when you can.",
  "Let's hang out this weekend.",
  "I'm thinking of you.",
  "Safe travels!",
  "Get well soon.",
  "I'm so sorry.",
  "Can you send me the details?",
  "I'm running late.",
  "I'll be there in 5 minutes.",
  "What time are we meeting?",
  "Let's go for a walk.",
  "Dinner tonight?",
  "What are your plans for the weekend?",
  "I hope you have a wonderful day!",
  "Just checking in.",
  "Don't forget about our meeting.",
  "I'll see you at the office.",
  "Take care!",
  "You're amazing!",
  "I appreciate you.",
  "Thanks for everything.",
  "Let's celebrate soon.",
  "I'm so proud of you.",
  "You're the best!",
  "Can I ask you a favor?",
  "I'm feeling a bit down today.",
  "Any plans for tonight?",
  "Let's grab coffee sometime.",
  "I'm free this afternoon.",
  "Do you need anything?",
  "I'll bring the snacks.",
  "I can't wait to see you.",
  "You're invited!",
  "It's been a while.",
  "I need to talk to you about something.",
  "I'm thinking about you.",
  "You make me smile.",
  "Let's go on an adventure.",
  "I can't stop thinking about you.",
  "I hope everything is going well.",
  "Please let me know if you need anything.",
  "You're in my thoughts.",
  "Looking forward to our meeting.",
  "I hope you had a good day.",
  "I'm here for you.",
  "Let's plan something fun.",
  "How was your day?",
  "Good night, talk to you tomorrow.",
  "I'm so happy for you!",
  "You're doing great!",
  "Let's make some memories.",
  "I believe in you.",
  "Can we reschedule?",
  "I'm sorry I missed your call.",
  "Do you have any updates?",
  "Let's work together on this.",
  "How's everything going?",
  "You're an inspiration.",
  "Let's take a break.",
  "Can we discuss this later?",
  "I just wanted to say hi.",
  "Wishing you all the best.",
  "Let's make today productive.",
  "I'm grateful for your support.",
  "You're a wonderful person.",
  "How can I assist you?",
  "I hope you enjoy your day!",
];
